---
homebrew_formulae:
  - git
  - zsh
  - bash-completion
  - curl
  - wget
  - httpie
  - node
  - python@3.13
  - python@3.14
  - go
  - php
  - maven
  - groovy
  - docker
  - docker-compose
  - kubernetes-cli
  - helm
  - minikube
  - kind
  - k9s
  - kubent
  - kubespy
  - argocd
  - krew
  - k3d
  - awscli
  - azure-cli
  - terraform
  - ansible
  - ansible-lint
  - packer
  - vault
  - consul
  - prometheus
  - grafana
  - htop
  - tmux
  - fzf
  - ripgrep
  - bat
  - fd
  - autojump
  - starship
  - zoxide
  - tree
  - jq
  - yq
  - gh
  - cheat
  - watch
  - colordiff
  - unzip
  - mysql
  - sqlite
  - libpq
  - wget
  - vim
  - nano

homebrew_casks:
  - chromium
  - docker
  - drawio
  - fig
  - kitty
  - kubenav
  - kubernetic
  - meld
  - multipass
  - postman
  - stats
  - termius
  - utm
  - vagrant
  - vagrant-vmware-utility
